local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.RAINFORESTTREE = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_SHORT = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_NORMAL = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_TALL = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_BURNT = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_STUMP = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_SAPLING = "Rainforest Tree Sapling"
STRINGS.NAMES.RAINFORESTTREE_CONE = "Rainforest Tree Cone"
STRINGS.RECIPE_DESC.RAINFORESTTREE_SAPLING = "Rainforest Sapling"
STRINGS.RECIPE_DESC.RAINFORESTTREE_CONE = "Rainforest Tree Cone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE = "Is this tree from here?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_CONE = "Weird tree cone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_SAPLING = "Weird tree sapling."

STRINGS.NAMES.RAINFORESTTREE_ROT = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_ROT_SHORT = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_ROT_NORMAL = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_ROT_TALL = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_ROT_BURNT = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_ROT_STUMP = "Rainforest Tree"

STRINGS.NAMES.CLAWPALMTREE = "Clawpalm Tree"
STRINGS.NAMES.CLAWPALMTREE_NORMAL = "Clawpalm Tree"
STRINGS.NAMES.CLAWPALMTREE_SHORT = "Clawpalm Tree"
STRINGS.NAMES.CLAWPALMTREE_TALL = "Clawpalm Tree"
STRINGS.NAMES.CLAWPALMTREE_BURNT = "Clawpalm Tree"
STRINGS.NAMES.CLAWPALMTREE_STUMP = "Clawpalm Tree"
STRINGS.NAMES.CLAWPALMTREE_SAPLING = "Clawpalm Tree Sapling"
STRINGS.NAMES.CLAWPALMTREE_CONE = "Clawpalm Tree Cone"
STRINGS.RECIPE_DESC.CLAWPALMTREE_SAPLING = "Clawpalm Sapling"
STRINGS.RECIPE_DESC.CLAWPALMTREE_CONE = "Clawpalm Tree Cone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWPALMTREE = "What a huge tree!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWPALMTREE_CONE = "Big tree cone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWPALMTREE_SAPLING = "Big tree sapling."

STRINGS.NAMES.ALOE_PLANTED = "Aloe"
STRINGS.RECIPE_DESC.ALOE_PLANTED = "Plant Aloes."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALOE_PLANTED = "Small green plant. How weird."

STRINGS.NAMES.FLOWER_RAINFOREST = "Exotic Flower"
STRINGS.RECIPE_DESC.FLOWER_RAINFOREST = "Plant Exotic Flowers."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLOWER_RAINFOREST = "These flowers are nice."

STRINGS.NAMES.PUGALISK_FOUNTAIN = "Fountain of Youth"
STRINGS.RECIPE_DESC.PUGALISK_FOUNTAIN = "Live forever."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PUGALISK_FOUNTAIN = "I can be immortal!"

STRINGS.NAMES.NETTLE = "Nettle"
STRINGS.NAMES.NETTLE = "Nettle"
STRINGS.RECIPE_DESC.NETTLE = "Plant Nettles."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NETTLE = "What a nice plant!"

STRINGS.NAMES.TUBERTREE = "Tuber Tree"
STRINGS.NAMES.TUBERTREE_SHORT = "Tuber Tree"
STRINGS.NAMES.TUBERTREE_TALL = "Tuber Tree"
STRINGS.NAMES.TUBERTREE_STUMP = "Tuber Tree"
STRINGS.NAMES.TUBERTREE_BURNT = "Tuber Tree"
STRINGS.RECIPE_DESC.TUBERTREE_SHORT = "Plant Tuber Trees."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREE = "What kind of tree is this?"

STRINGS.NAMES.GRASS_TALL2 = "Tall Grass"
STRINGS.RECIPE_DESC.GRASS_TALL2 = "Plant Tall Grass."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_TALL2 = "Grass, but tall?"

STRINGS.NAMES.SMELTER = "Smelter"
STRINGS.RECIPE_DESC.SMELTER = "Malfunctioning Machine."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SMELTER = "Where do I turn on this thing?"

STRINGS.NAMES.TURF_COBBLEROAD = "Stone Road Turf"
STRINGS.RECIPE_DESC.TURF_COBBLEROAD = "Cobblestone cousin."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_COBBLEROAD = "A better road!"

STRINGS.NAMES.TURF_DEEPRAINFOREST = "Rainforest Turf"
STRINGS.RECIPE_DESC.TURF_DEEPRAINFOREST = "Deep Forest Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_DEEPRAINFOREST = "Deep forest, spooky!"

STRINGS.NAMES.TURF_FIELDS = "Cultivated Turf"
STRINGS.RECIPE_DESC.TURF_FIELDS = "Farmlands Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_FIELDS = "Turf of farms."

STRINGS.NAMES.TURF_FOUNDATION = "Flat Stone Turf"
STRINGS.RECIPE_DESC.TURF_FOUNDATION = "Rocky cousin."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_FOUNDATION = "Flat Stones oh!"

STRINGS.NAMES.TURF_GASJUNGLE = "Gas Jungle Turf"
STRINGS.RECIPE_DESC.TURF_GASJUNGLE = "Twitch loves this one."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_GASJUNGLE = "Rexxxxxxxxxxxxxxxxpeita o rato!"

STRINGS.NAMES.TURF_CHECKEREDLAWN = "Lawn Turf"
STRINGS.RECIPE_DESC.TURF_CHECKEREDLAWN = "Checkered Floor copy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CHECKEREDLAWN = "This turf is so beautiful!"

STRINGS.NAMES.TURF_MOSS = "Moss Turf"
STRINGS.RECIPE_DESC.TURF_MOSS = "Mossy Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MOSS = "What is this turf?"

STRINGS.NAMES.TURF_PIGRUINS = "Pig Ruins Turf"
STRINGS.RECIPE_DESC.TURF_PIGRUINS = "Ancient Pig Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_PIGRUINS = "It's more old than me!"

STRINGS.NAMES.TURF_RAINFOREST = "Rainforest Turf"
STRINGS.RECIPE_DESC.TURF_RAINFOREST = "Rainy Forest Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_RAINFOREST = "Strange Turf."

STRINGS.NAMES.TURF_ANTFLOOR = "Ant Turf"
STRINGS.RECIPE_DESC.TURF_ANTFLOOR = "Kill the ants!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ANTFLOOR = "Ahhhh, the ants."

STRINGS.NAMES.TURF_BATFLOOR = "Bat Turf"
STRINGS.RECIPE_DESC.TURF_BATFLOOR = "Kill the bats!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BATFLOOR = "Where is the bats the recipe said?"

STRINGS.NAMES.TURF_BATTLEGROUNDS = "Battlegrounds Turf"
STRINGS.RECIPE_DESC.TURF_BATTLEGROUNDS = "Victory Royale..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BATTLEGROUNDS = "I won the match?"

STRINGS.NAMES.TURF_BOG = "Bog Turf"
STRINGS.RECIPE_DESC.TURF_BOG = "There is iron inside this turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BOG = "Good place to mine some iron..."

STRINGS.NAMES.TURF_PLAINS = "Plains Turf"
STRINGS.RECIPE_DESC.TURF_PLAINS = "Green Savanna Edition!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_PLAINS = "It's so green and planty"

STRINGS.NAMES.TURF_BEARDRUG = "Beard Hair Rug"
STRINGS.RECIPE_DESC.TURF_BEARDRUG = "Made with human beard."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEARDRUG = "Ewwww."

STRINGS.NAMES.LAWNORNAMENT_1 = "Lawn Decoration"
STRINGS.RECIPE_DESC.LAWNORNAMENT_1 = "Fancy Tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAWNORNAMENT_1 = "It's beautiful"

STRINGS.NAMES.LAWNORNAMENT_2 = "Lawn Decoration"
STRINGS.RECIPE_DESC.LAWNORNAMENT_2 = "Fancy Tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAWNORNAMENT_2 = "It's beautiful"

STRINGS.NAMES.LAWNORNAMENT_3 = "Lawn Decoration"
STRINGS.RECIPE_DESC.LAWNORNAMENT_3 = "Fancy Small Tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAWNORNAMENT_3 = "It's beautiful"

STRINGS.NAMES.LAWNORNAMENT_4 = "Lawn Decoration"
STRINGS.RECIPE_DESC.LAWNORNAMENT_4 = "Fancy Small Tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAWNORNAMENT_4 = "It's beautiful"

STRINGS.NAMES.LAWNORNAMENT_5 = "Lawn Decoration"
STRINGS.RECIPE_DESC.LAWNORNAMENT_5 = "Fancy Mini Tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAWNORNAMENT_5 = "It's beautiful"

STRINGS.NAMES.LAWNORNAMENT_6 = "Lawn Decoration"
STRINGS.RECIPE_DESC.LAWNORNAMENT_6 = "Fancy Rose Bush."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAWNORNAMENT_6 = "It's beautiful"

STRINGS.NAMES.LAWNORNAMENT_7 = "Lawn Decoration"
STRINGS.RECIPE_DESC.LAWNORNAMENT_7 = "Fancy Pink Bush."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAWNORNAMENT_7 = "It's beautiful"

STRINGS.NAMES.WALL_PIG_RUINS_ITEM = "Ancient Pig Wall"
STRINGS.NAMES.WALL_PIG_RUINS = "Ancient Pig Wall"
STRINGS.RECIPE_DESC.WALL_PIG_RUINS_ITEM = "Make Ancient Walls."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_PIG_RUINS = "This is more old than me!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_PIG_RUINS_ITEM = "This is more old than me!"

STRINGS.NAMES.LAMP_POST = "Lamp Post"
STRINGS.RECIPE_DESC.LAMP_POST = "A Light of Hope."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMP_POST = "Much better now!"

STRINGS.NAMES.MANDRAKEHOUSE = "Elderdrake House"
STRINGS.RECIPE_DESC.MANDRAKEHOUSE = "House for.... Mandrakes?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANDRAKEHOUSE = "Why in the earth a mandrake have a house?"

STRINGS.NAMES.PUGALISK_RUINS_PILLAR = "Fountain Pillar"
STRINGS.RECIPE_DESC.PUGALISK_RUINS_PILLAR = "Ancient Pillars."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PUGALISK_RUINS_PILLAR = "Is that snake here?"

STRINGS.NAMES.PIG_RUINS_TORCH = "Crumbling Brazier"
STRINGS.RECIPE_DESC.PIG_RUINS_TORCH = "Eternal flame."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIG_RUINS_TORCH = "I can cook things in here!"

STRINGS.NAMES.ANTCOMBHOME = "Antcomb Home"
STRINGS.RECIPE_DESC.ANTCOMBHOME = "Honey, Honey and Honey!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTCOMBHOME = "Sweeeeeet!"

STRINGS.NAMES.ANT_CHEST = "Honey Box"
STRINGS.RECIPE_DESC.ANT_CHEST = "A Box full of Honey, or items..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANT_CHEST = "To store my honey or my items."

STRINGS.NAMES.ANT_HONEY_CACHE = "Honey Cache"
STRINGS.RECIPE_DESC.ANT_HONEY_CACHE = "Honey Storage."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANT_HONEY_CACHE = "I want that honey!"

STRINGS.NAMES.ROCK_FLIPPABLE = "Stone Slab"
STRINGS.RECIPE_DESC.ROCK_FLIPPABLE = "Flippable stones."
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_FLIPPABLE = "Weird rock." -- Actually the prefab has a existing string lol;

STRINGS.NAMES.PIGSTATUE_ANT = "Crumbling Visage"
STRINGS.RECIPE_DESC.PIGSTATUE_ANT = "Statue of a Ant."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGSTATUE_ANT = "Looks sick!"

STRINGS.NAMES.PIGSTATUE_IDOL = "Crumbling Visage"
STRINGS.RECIPE_DESC.PIGSTATUE_IDOL = "Statue of a Ancient Idol."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGSTATUE_IDOL = "An ancient Idol."

STRINGS.NAMES.PIGSTATUE_PIG = "Crumbling Visage"
STRINGS.RECIPE_DESC.PIGSTATUE_PIG = "Statue of a Pig."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGSTATUE_PIG = "Pig King??"

STRINGS.NAMES.SMASHINGPOT = "Smashing Pot"
STRINGS.RECIPE_DESC.SMASHINGPOT = "Ancient Vase."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SMASHINGPOT = "What is inside?"

STRINGS.NAMES.HAMLET_HOUSE1 = "Pig Townhouse"
STRINGS.RECIPE_DESC.HAMLET_HOUSE1 = "Brown House."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAMLET_HOUSE1 = "What a beautiful house for a pig!"

STRINGS.NAMES.HAMLET_HOUSE2 = "Pig Townhouse"
STRINGS.RECIPE_DESC.HAMLET_HOUSE2 = "White House."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAMLET_HOUSE2 = "What a beautiful house for a pig!"

STRINGS.NAMES.HAMLET_HOUSE3 = "Pig Townhouse"
STRINGS.RECIPE_DESC.HAMLET_HOUSE3 = "Green House."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAMLET_HOUSE3 = "What a beautiful house for a pig!"

STRINGS.NAMES.HAMLET_HOUSE4 = "Pig Townhouse"
STRINGS.RECIPE_DESC.HAMLET_HOUSE4 = "Pink House."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAMLET_HOUSE4 = "What a beautiful house for a pig!"

STRINGS.NAMES.HAMLET_HOUSE5 = "Pig Townhouse"
STRINGS.RECIPE_DESC.HAMLET_HOUSE5 = "Beige House."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAMLET_HOUSE5 = "What a beautiful house for a pig!"

STRINGS.NAMES.HAMLET_HOUSE6 = "Pig Townhouse"
STRINGS.RECIPE_DESC.HAMLET_HOUSE6 = "Red House."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAMLET_HOUSE6 = "What a beautiful house for a pig!"